### ISSUE TITLE
onItemClickListener

### ISSUE THREAD

**Issue by SirLordPouya** [shuhart/StepView#20]
Hi
is there a way to add onItemClickListener method that returns the position of item that user has clicked on?
thanks

**Comment by shuhart** [comment]
Not yet. I will think about it when I find spare time.

**Comment by ArlonTM** [comment]
Hi. 
This feature will be so cool. Otherwise, if you don't find time to implement such a feature, you could just expose the **_getCirclePositions()_** and **_getCirclePositionsWithText()_** to allow a third-party to extend your class and handle the touch event by matching the circles' positions with touch coordinates.
Thanks

**Comment by shuhart** [comment]
Now in 1.3.1 you can use OnStepClickListener. The clickable area include not only a circle with text but a big square around each step. No visual feedback can be provided, unfortunately.
